In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/cars.csv')

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.sample(10)

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,body_type,has_warranty,state,drivetrain,price_usd,is_exchangeable,location_region,number_of_photos,up_counter,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
12173,Renault,Espace,mechanical,black,176643,2015,diesel,False,diesel,1.6,minivan,False,owned,front,13207.05,False,Минская обл.,6,14,True,False,False,False,False,False,False,False,False,False,110
14703,Seat,Cordoba,mechanical,red,300000,1997,gasoline,False,gasoline,1.4,coupe,False,owned,front,900.00,True,Гродненская обл.,11,20,False,False,False,False,False,False,False,False,False,True,51
28524,BMW,X4,automatic,black,96357,2015,gasoline,False,gasoline,2.0,suv,False,owned,all,31000.00,True,Минская обл.,18,19,False,True,True,False,True,True,True,False,True,True,37
37446,Peugeot,107,automatic,blue,88000,2010,gasoline,False,gasoline,1.0,hatchback,False,owned,front,5600.00,False,Витебская обл.,8,2,False,True,False,False,False,False,False,False,False,False,58
34402,Mercedes-Benz,E350,automatic,black,225000,2012,gasoline,False,gasoline,3.5,coupe,False,owned,all,22000.00,False,Минская обл.,12,76,False,True,True,True,True,True,True,True,True,True,454
32063,Skoda,Rapid,mechanical,other,0,2019,gasoline,False,gasoline,1.6,sedan,True,new,front,16924.03,True,Минская обл.,15,2,True,False,False,False,False,False,False,False,False,False,2
38188,Chrysler,Pacifica,automatic,green,320000,2005,gas,True,gasoline,3.5,universal,False,owned,front,4950.00,True,Гродненская обл.,6,22,True,False,False,False,False,False,False,False,False,False,29
10314,Ford,Mondeo,mechanical,blue,500000,1994,gasoline,False,gasoline,1.8,universal,False,emergency,front,260.83,False,Минская обл.,1,1,False,True,False,False,False,False,False,False,False,False,3
28129,BMW,525,mechanical,red,196,1994,diesel,False,diesel,2.5,sedan,False,owned,rear,2000.00,False,Витебская обл.,7,6,False,False,False,False,False,True,False,False,False,True,7
10035,Ford,Mondeo,mechanical,black,346000,1996,gasoline,False,gasoline,1.8,universal,False,owned,front,1350.00,False,Гродненская обл.,22,7,False,False,False,False,False,False,False,False,False,True,12

In [ ]:
df.shape

(38531, 30)

In [ ]:
categorical_data = df.select_dtypes(include=['object', 'bool'])

In [ ]:
categorical_data = categorical_data.astype(str)

In [ ]:
categorical_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38531 entries, 0 to 38530
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38531 non-null  object
 1   model_name         38531 non-null  object
 2   transmission       38531 non-null  object
 3   color              38531 non-null  object
 4   engine_fuel        38531 non-null  object
 5   engine_has_gas     38531 non-null  object
 6   engine_type        38531 non-null  object
 7   body_type          38531 non-null  object
 8   has_warranty       38531 non-null  object
 9   state              38531 non-null  object
 10  drivetrain         38531 non-null  object
 11  is_exchangeable    38531 non-null  object
 12  location_region    38531 non-null  object
 13  feature_0          38531 non-null  object
 14  feature_1          38531 non-null  object
 15  feature_2          38531 non-null  object
 16  feature_3          38531 non-null  object
 17  feature_4          38531 non-null  object
 18  feature_5          38531 non-null  object
 19  feature_6          38531 non-null  object
 20  feature_7          38531 non-null  object
 21  feature_8          38531 non-null  object
 22  feature_9          38531 non-null  object
dtypes: object(23)
memory usage: 6.8+ MB

In [ ]:
categorical_data.head(6)

,manufacturer_name,model_name,transmission,color,engine_fuel,engine_has_gas,engine_type,body_type,has_warranty,state,drivetrain,is_exchangeable,location_region,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9
0,Subaru,Outback,automatic,silver,gasoline,False,gasoline,universal,False,owned,all,False,Минская обл.,False,True,True,True,False,True,False,True,True,True
1,Subaru,Outback,automatic,blue,gasoline,False,gasoline,universal,False,owned,all,True,Минская обл.,False,True,False,False,True,True,False,False,False,True
2,Subaru,Forester,automatic,red,gasoline,False,gasoline,suv,False,owned,all,True,Минская обл.,False,True,False,False,False,False,False,False,True,True
3,Subaru,Impreza,mechanical,blue,gasoline,False,gasoline,sedan,False,owned,all,True,Минская обл.,True,False,False,False,False,False,False,False,False,False
4,Subaru,Legacy,automatic,black,gasoline,False,gasoline,universal,False,owned,all,True,Гомельская обл.,False,True,False,True,True,False,False,False,False,True
5,Subaru,Outback,automatic,silver,gasoline,False,gasoline,universal,False,owned,all,True,Минская обл.,False,True,False,False,False,True,False,True,True,True

# Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['mechanical','automatic'],['gasoline','gas','diesel','hybrid-diesel','hybrid-petrol','electric'],
                                ['True','False'],['gasoline','diesel','electric'],['False','True'],['emergency','owned','new'],
                                ['True','False'],['False','True'],['False','True'],['False','True'],['False','True'],['False','True'],
                                ['False','True'],['False','True'],['False','True'],['False','True'],['False','True']],dtype=np.int32)

In [ ]:
OE_data['state'].value_counts()

owned        37723
new            438
emergency      370
Name: state, dtype: int64

In [ ]:
OE_data.head()

,transmission,engine_fuel,engine_has_gas,engine_type,has_warranty,state,drivetrain,is_exchangeable,location_region,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9
0,automatic,gasoline,False,gasoline,False,owned,all,False,Минская обл.,False,True,True,True,False,True,False,True,True,True
1,automatic,gasoline,False,gasoline,False,owned,all,True,Минская обл.,False,True,False,False,True,True,False,False,False,True
2,automatic,gasoline,False,gasoline,False,owned,all,True,Минская обл.,False,True,False,False,False,False,False,False,True,True
3,mechanical,gasoline,False,gasoline,False,owned,all,True,Минская обл.,True,False,False,False,False,False,False,False,False,False
4,automatic,gasoline,False,gasoline,False,owned,all,True,Гомельская обл.,False,True,False,True,True,False,False,False,False,True

In [ ]:
oe_clean_data = oe.fit_transform(OE_data[['transmission','engine_fuel','engine_has_gas','engine_type','has_warranty','state',
                          'is_exchangeable','feature_0','feature_1','feature_2','feature_3','feature_4',
                          'feature_5','feature_6','feature_7','feature_8','feature_9']])

In [ ]:
oe_clean_data = pd.DataFrame(oe_clean_data,columns=['transmission','engine_fuel','engine_has_gas','engine_type','has_warranty','state',
                          'is_exchangeable','feature_0','feature_1','feature_2','feature_3','feature_4',
                          'feature_5','feature_6','feature_7','feature_8','feature_9'])

In [ ]:
oe_clean_data.head(3)

,transmission,engine_fuel,engine_has_gas,engine_type,has_warranty,state,is_exchangeable,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9
0,1,0,1,0,0,1,1,0,1,1,1,0,1,0,1,1,1
1,1,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,1
2,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,1

## **One-Hot-Encoding**

In [ ]:
one_hot_encod_data = df[['color','body_type','drivetrain']]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder( sparse=False, dtype=np.int32)

In [ ]:
ohe_encode_data = ohe.fit_transform(one_hot_encod_data)
ohe_encode_data.shape

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

(38531, 27)

In [ ]:
ohe_encode_data.shape

(38531, 27)

In [ ]:
ohe.categories_

[array(['black', 'blue', 'brown', 'green', 'grey', 'orange', 'other',
        'red', 'silver', 'violet', 'white', 'yellow'], dtype=object),
 array(['cabriolet', 'coupe', 'hatchback', 'liftback', 'limousine',
        'minibus', 'minivan', 'pickup', 'sedan', 'suv', 'universal', 'van'],
       dtype=object),
 array(['all', 'front', 'rear'], dtype=object)]

In [ ]:
ohe_clean_data = pd.DataFrame(ohe_encode_data,columns=['black', 'blue', 'brown', 'green', 'grey', 'orange', 'other',
        'red', 'silver', 'violet', 'white', 'yellow','cabriolet', 'coupe', 'hatchback', 'liftback', 'limousine',
        'minibus', 'minivan', 'pickup', 'sedan', 'suv', 'universal', 'van','all', 'front', 'rear'])

In [ ]:
ohe_clean_data.drop(['black','cabriolet','all'],axis=1,inplace=True)

In [ ]:
ohe_clean_data.shape

(38531, 24)

In [ ]:
ohe_clean_data.head(3)

,blue,brown,green,grey,orange,other,red,silver,violet,white,yellow,coupe,hatchback,liftback,limousine,minibus,minivan,pickup,sedan,suv,universal,van,front,rear
0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [ ]:
categorical_df = pd.concat([oe_clean_data,ohe_clean_data],axis=1)
categorical_df.shape

(38531, 41)

In [ ]:
categorical_df.shape

(38531, 41)

# Pd.Get_Dummies

In [ ]:
manu_count = df['manufacturer_name'].value_counts()

In [ ]:
model_count = df['model_name'].value_counts()

In [ ]:
manu = 250

In [ ]:
model_c = 150

In [ ]:
manu_repl = manu_count[manu_count <= manu].keys()

In [ ]:
model_repl = model_count[model_count <= model_c].keys()

In [ ]:
manufacture_df = pd.get_dummies(df['manufacturer_name'].replace(manu_repl,'uncommon_manufactur'))

In [ ]:
model_name_df = pd.get_dummies(df['model_name'].replace(model_repl,'uncommon_model_name'))

In [ ]:
categorical_ohe_df = pd.concat([manufacture_df,model_name_df],axis=1)

In [ ]:
categorical_ohe_df.shape

(38531, 122)

In [ ]:
categorical_ohe_df.sample(5)

,Audi,BMW,Chevrolet,Chrysler,Citroen,Dodge,Fiat,Ford,Honda,Hyundai,Kia,Mazda,Mercedes-Benz,Mitsubishi,Nissan,Opel,Peugeot,Renault,Seat,Skoda,Subaru,Toyota,Volkswagen,Volvo,uncommon_manufactur,ВАЗ,100,206,3,307,308,316,318,320,323,406,407,520,525,530,6,605,626,730,80,A4,A6,A8,Accent,Accord,Almera,Astra,Avensis,C180,C4,C5,Camry,Cee'd,Civic,Corolla,Corsa,Cruze,Daily,E200,E220,Escort,Espace,Fabia,Fiesta,Focus,Fusion,Galant,Galaxy,Golf,Grand Scenic,Insignia,Jetta,Kodiaq,Laguna,Lancer,Logan,Marea,Megane,Megane Scenic,Mondeo,Octavia,Omega,Outlander,Passat,Polo,Polo Sedan,Primera,Punto,Qashqai,RAV4,Rapid,Rio,S60,S80,Santa Fe,Scenic,Sharan,Solaris,Sonata,Sorento,Sportage,Sprinter,Superb,T4,Tiguan,Touareg,Touran,Transit,Vectra,Vito,X5,XC90,Xantia,Xsara,Yaris,Zafira,uncommon_model_name
1991,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28399,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29354,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22921,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:
categorical_new_df = pd.concat([categorical_ohe_df,categorical_df],axis=1)

In [ ]:
categorical_new_df.head(5)

,Audi,BMW,Chevrolet,Chrysler,Citroen,Dodge,Fiat,Ford,Honda,Hyundai,Kia,Mazda,Mercedes-Benz,Mitsubishi,Nissan,Opel,Peugeot,Renault,Seat,Skoda,Subaru,Toyota,Volkswagen,Volvo,uncommon_manufactur,ВАЗ,100,206,3,307,308,316,318,320,323,406,407,520,525,530,6,605,626,730,80,A4,A6,A8,Accent,Accord,Almera,Astra,Avensis,C180,C4,C5,Camry,Cee'd,Civic,Corolla,Corsa,Cruze,Daily,E200,E220,Escort,Espace,Fabia,Fiesta,Focus,Fusion,Galant,Galaxy,Golf,Grand Scenic,Insignia,Jetta,Kodiaq,Laguna,Lancer,Logan,Marea,Megane,Megane Scenic,Mondeo,Octavia,Omega,Outlander,Passat,Polo,Polo Sedan,Primera,Punto,Qashqai,RAV4,Rapid,Rio,S60,S80,Santa Fe,Scenic,Sharan,Solaris,Sonata,Sorento,Sportage,Sprinter,Superb,T4,Tiguan,Touareg,Touran,Transit,Vectra,Vito,X5,XC90,Xantia,Xsara,Yaris,Zafira,uncommon_model_name,transmission,engine_fuel,engine_has_gas,engine_type,has_warranty,state,is_exchangeable,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,blue,brown,green,grey,orange,other,red,silver,violet,white,yellow,coupe,hatchback,liftback,limousine,minibus,minivan,pickup,sedan,suv,universal,van,front,rear
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,1,0,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [ ]:
categorical_new_df

# Handle_Numerical_Columns

In [ ]:
numerical_cols = df.select_dtypes(include=['int64','float64'])

In [ ]:
numerical_cols.head(6)

,odometer_value,year_produced,engine_capacity,price_usd,number_of_photos,up_counter,duration_listed
0,190000,2010,2.5,10900.00,9,13,16
1,290000,2002,3.0,5000.00,12,54,83
2,402000,2001,2.5,2800.00,4,72,151
3,10000,1999,3.0,9999.00,9,42,86
4,280000,2001,2.5,2134.11,14,7,7
5,132449,2011,2.5,14700.00,20,56,67

In [ ]:
numerical_cols.shape

(38531, 7)

In [ ]:
numerical_cols.isnull().sum()

odometer_value       0
year_produced        0
engine_capacity     10
price_usd            0
number_of_photos     0
up_counter           0
duration_listed      0
dtype: int64

In [ ]:
numerical_cols = numerical_cols.dropna()

In [ ]:
numerical_cols.isnull().sum().sum()

0

In [ ]:
numerical_cols.head(5)

,odometer_value,year_produced,engine_capacity,price_usd,number_of_photos,up_counter,duration_listed
0,190000,2010,2.5,10900.00,9,13,16
1,290000,2002,3.0,5000.00,12,54,83
2,402000,2001,2.5,2800.00,4,72,151
3,10000,1999,3.0,9999.00,9,42,86
4,280000,2001,2.5,2134.11,14,7,7

In [ ]:
numerical_cols.describe()

,odometer_value,year_produced,engine_capacity,price_usd,number_of_photos,up_counter,duration_listed
count,38521.000000,38521.000000,38521.000000,38521.000000,38521.000000,38521.000000,38521.000000
mean,248910.074427,2002.940863,2.055161,6637.160884,9.648062,16.306586,80.584616
std,136059.499858,8.064761,0.671178,6425.198996,6.092860,43.291786,112.838577
min,0.000000,1942.000000,0.200000,1.000000,1.000000,1.000000,0.000000
25%,158000.000000,1998.000000,1.600000,2100.000000,5.000000,2.000000,23.000000
50%,250000.000000,2003.000000,2.000000,4800.000000,8.000000,5.000000,59.000000
75%,325000.000000,2009.000000,2.300000,8950.000000,12.000000,16.000000,91.000000
max,1000000.000000,2019.000000,8.000000,50000.000000,86.000000,1861.000000,2232.000000

In [ ]:
df_new = pd.concat([categorical_new_df,numerical_cols],axis=1)

In [ ]:
df_new.to_csv('Cars_Clean_Data.csv')

In [ ]:
df_new.to_csv('file2.csv')

In [ ]:
df_new.head(3)

,Audi,BMW,Chevrolet,Chrysler,Citroen,Dodge,Fiat,Ford,Honda,Hyundai,Kia,Mazda,Mercedes-Benz,Mitsubishi,Nissan,Opel,Peugeot,Renault,Seat,Skoda,Subaru,Toyota,Volkswagen,Volvo,uncommon_manufactur,ВАЗ,100,206,3,307,308,316,318,320,323,406,407,520,525,530,6,605,626,730,80,A4,A6,A8,Accent,Accord,Almera,Astra,Avensis,C180,C4,C5,Camry,Cee'd,Civic,Corolla,Corsa,Cruze,Daily,E200,E220,Escort,Espace,Fabia,Fiesta,Focus,Fusion,Galant,Galaxy,Golf,Grand Scenic,Insignia,Jetta,Kodiaq,Laguna,Lancer,Logan,Marea,Megane,Megane Scenic,Mondeo,Octavia,Omega,Outlander,Passat,Polo,Polo Sedan,Primera,Punto,Qashqai,RAV4,Rapid,Rio,S60,S80,Santa Fe,Scenic,Sharan,Solaris,Sonata,Sorento,Sportage,Sprinter,Superb,T4,Tiguan,Touareg,Touran,Transit,Vectra,Vito,X5,XC90,Xantia,Xsara,Yaris,Zafira,uncommon_model_name,transmission,engine_fuel,engine_has_gas,engine_type,has_warranty,state,is_exchangeable,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,blue,brown,green,grey,orange,other,red,silver,violet,white,yellow,coupe,hatchback,liftback,limousine,minibus,minivan,pickup,sedan,suv,universal,van,front,rear,odometer_value,year_produced,engine_capacity,price_usd,number_of_photos,up_counter,duration_listed
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,1,0,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,190000.0,2010.0,2.5,10900.0,9.0,13.0,16.0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,290000.0,2002.0,3.0,5000.0,12.0,54.0,83.0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,402000.0,2001.0,2.5,2800.0,4.0,72.0,151.0

# **Column Transform**

In [71]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [99]:
data = pd.read_csv('/content/bank_marketing_dataset.csv')

In [100]:
pd.set_option('display.max_columns',None)

In [101]:
data.shape

(41188, 21)

In [102]:
data.shape

(41188, 21)

In [103]:
data.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [104]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  subscribed      41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [105]:
data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
subscribed        0
dtype: int64

Column tranformation

In [111]:
transformer = ColumnTransformer(transformers=[
    ('trf1',OrdinalEncoder(categories=[['unknown','student','unemployed','housemaid','retired','admin.','self-employed',
                                         'technician','blue-collar','services','management','entrepreneur'],
                                        ['unknown','illiterate','high.school','basic.4y','basic.6y','basic.9y','university.degree','professional.course'],
                                        ['unknown','no','yes'],['unknown','no','yes'],['no','yes']]),
                                        ['job','education','default','housing','subscribed']),
      
    ('trf2',OneHotEncoder(sparse=False, drop='first',dtype=np.int32),
    ['marital','contact','month','day_of_week','poutcome'])
],remainder='passthrough')

In [112]:
data.head(6)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,subscribed
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,198,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [113]:
data['default'].value_counts()

no         32588
unknown     8597
yes            3
Name: default, dtype: int64

In [115]:
transform_data = transformer.fit_transform(data)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [119]:
df = data.copy()

In [120]:
transform_data.shape

(41188, 35)

In [121]:
data.values.shape

(41188, 21)

In [122]:
data.drop(['job','marital','education','default','housing','contact','month','day_of_week','poutcome','subscribed'],axis=1,inplace=True)

In [123]:
new_data = np.concatenate([data.values,transform_data],axis=1)

array([[56, 'no', 261, ..., -36.4, 4.857, 5191.0],
       [57, 'no', 149, ..., -36.4, 4.857, 5191.0],
       [37, 'no', 226, ..., -36.4, 4.857, 5191.0],
       ...,
       [56, 'no', 189, ..., -50.8, 1.028, 4963.6],
       [44, 'no', 442, ..., -50.8, 1.028, 4963.6],
       [74, 'no', 239, ..., -50.8, 1.028, 4963.6]], dtype=object)